# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  no_epoch_checkpoints: true
  best_checkpoint_metric: uer
  save_interval: 40

task:
  _name: audio_finetuning
  data: ???
  normalize: true
  labels: phn

dataset:
  num_workers: 6
  max_tokens: 1280000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 500 #10000
  validate_interval: 50
  valid_subset: valid
  train_subset: train

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 1

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 18000
  lr: [0.0001]
  sentence_avg: true
  update_freq: [8]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: distilxlsr_ctc
  w2v_path: ???
  encoder_last_layer: ???
  prune_model: true
  apply_mask: true
  mask_prob: 0.55
  mask_channel_prob: 0.25
  mask_channel_length: 64
  encoder_layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000
  